version: "3.10"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=fitmeet
      - POSTGRES_USER=fitmeet
      - POSTGRES_PASSWORD=fitmeet

  # redis:
  #   image: redis
  #   restart: always
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   command: "redis-server"
  #   ports:
  #     - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      # debug
      #- "4000:4000"
    environment:
      - POSTGRES_NAME=fitmeet
      - POSTGRES_USER=fitmeet
      - POSTGRES_PASSWORD=fitmeet
      - DEBUG=True

    depends_on:
      - db

